apiVersion: apps/v1
kind: Deployment
metadata:
name: zigzag-deployment
labels:
app: zigzag
spec:
replicas: 1
selector:
matchLabels:
app: zigzag
template:
metadata:
labels:
app: zigzag
spec:
containers:
  - name: zigzag-container
image: registry.forge.hefr.ch/gaetan.cogliati/ps5-zigzag:1.0.6
imagePullPolicy: Always
env:
  - name: URL_PREFIX
value: /zigzag
ports:
  - containerPort: 8080
imagePullSecrets:
  - name: regcred2
---
apiVersion: v1
kind: Service
metadata:
name: zigzag
spec:
selector:
app: zigzag
ports:
  - protocol: TCP
port: 8080
targetPort: 8080